//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicNodesTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicNodesTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Name=&quot;oldtest&quot; xmlns:yaxlib=&quot;http://www.sinairv.com/yaxlib/&quot;&gt;
        ///  &lt;Network Sequential=&quot;False&quot; LoadOnStart=&quot;False&quot; SaveOnStop=&quot;False&quot; Id=&quot;0&quot; Name=&quot;Network&quot;&gt;
        ///    &lt;Children&gt;
        ///      &lt;MyRandomNode LoadOnStart=&quot;False&quot; SaveOnStop=&quot;False&quot; Id=&quot;6&quot; Name=&quot;Node_6&quot; yaxlib:realtype=&quot;GoodAI.Modules.Common.MyRandomNode&quot;&gt;
        ///        &lt;SingleOutput&gt;False&lt;/SingleOutput&gt;
        ///        &lt;IO&gt;
        ///          &lt;OutputSize&gt;1&lt;/OutputSize&gt;
        ///        &lt;/IO&gt;
        ///        &lt;ColumnHint&gt;1&lt;/ColumnHint&gt;
        ///        &lt;DataFolder&gt;&lt;/DataFolder&gt;
        ///        &lt;Locat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Convert9To10XML {
            get {
                return ResourceManager.GetString("Convert9To10XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Project Name=&quot;oldtest&quot; xmlns:yaxlib=&quot;http://www.sinairv.com/yaxlib/&quot;&gt;
        ///  &lt;Network Sequential=&quot;False&quot; LoadOnStart=&quot;False&quot; SaveOnStop=&quot;False&quot; Id=&quot;0&quot; Name=&quot;Network&quot;&gt;
        ///    &lt;Children&gt;
        ///      &lt;MyRandomNode LoadOnStart=&quot;False&quot; SaveOnStop=&quot;False&quot; Id=&quot;6&quot; Name=&quot;Node_6&quot; yaxlib:realtype=&quot;GoodAI.Modules.Common.MyRandomNode&quot;&gt;
        ///        &lt;SingleOutput&gt;False&lt;/SingleOutput&gt;
        ///        &lt;IO&gt;
        ///          &lt;OutputSize&gt;1&lt;/OutputSize&gt;
        ///        &lt;/IO&gt;
        ///        &lt;ColumnHint&gt;1&lt;/ColumnHint&gt;
        ///        &lt;DataFolder&gt;&lt;/DataFolder&gt;
        ///        &lt;Locat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Convert9To10XMLResult {
            get {
                return ResourceManager.GetString("Convert9To10XMLResult", resourceCulture);
            }
        }
    }
}
